apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deploy
  labels: 
    app: web
  annotations: 
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-app
          image: nginx:alpine

---

apiVersion: v1 
kind: Service
metadata:
  name: my-service
  labels:
    app: apa-dep
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
